#%RAML 1.0 NamedExample

value:
 Identification:
    FirstName: Bob
    LastName: Fredric
    DOB: 21 June 1980
    Gender: M
    Title: Manager
 Address:
    type: home
    number: 1234
    street: bla bla st
    Unit: 1A
    City: Columbus
    State: OH
    zipcode: 12345
 Communication:
  email: abc@gmail.com
  cell: +1 5555555555
 